// Extended crop database with 100+ produce types

export const extendedProduceSeedData = {
  // ==================== GRAINS & CEREALS ====================
  grains: [
    {
      name: "Barley",
      scientificName: "Hordeum vulgare",
      category: "CROPS",
      description: "Versatile cereal grain for food, feed, and brewing",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1.5,
      plantSpacing: 1,
      rowSpacing: 7,
      germinationDays: 7,
      daysToMaturity: 90,
      matureHeight: 3,
      companionPlants: ["legumes"],
      commonPests: ["aphids", "armyworm"],
      commonDiseases: ["rust", "powdery mildew"]
    },
    {
      name: "Oats",
      scientificName: "Avena sativa",
      category: "CROPS",
      description: "Nutritious whole grain cereal",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 1,
      rowSpacing: 7,
      germinationDays: 10,
      daysToMaturity: 100,
      matureHeight: 4,
      companionPlants: ["clover"],
      commonPests: ["aphids", "armyworm"],
      commonDiseases: ["crown rust", "stem rust"]
    },
    {
      name: "Rye",
      scientificName: "Secale cereale",
      category: "CROPS",
      description: "Hardy grain crop for bread and whiskey",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 7,
      soilTypes: ["SANDY", "SANDY_LOAM", "LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 1,
      rowSpacing: 6,
      germinationDays: 7,
      daysToMaturity: 120,
      matureHeight: 5,
      droughtTolerant: true,
      coldTolerant: true,
      companionPlants: ["vetch"],
      commonPests: ["aphids"],
      commonDiseases: ["ergot", "rust"]
    },
    {
      name: "Sorghum",
      scientificName: "Sorghum bicolor",
      category: "CROPS",
      description: "Drought-tolerant grain for arid regions",
      climateZones: ["ARID", "SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM", "CLAY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 8.5,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 6,
      rowSpacing: 30,
      germinationDays: 10,
      daysToMaturity: 110,
      matureHeight: 5,
      droughtTolerant: true,
      heatTolerant: true,
      companionPlants: ["cowpeas"],
      commonPests: ["sorghum midge", "aphids"],
      commonDiseases: ["anthracnose", "head smut"]
    },
    {
      name: "Millet",
      scientificName: "Pennisetum glaucum",
      category: "CROPS",
      description: "Small-seeded grain for dry climates",
      climateZones: ["ARID", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.5,
      waterRequirement: "VERY_LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 2,
      rowSpacing: 12,
      germinationDays: 5,
      daysToMaturity: 65,
      matureHeight: 4,
      droughtTolerant: true,
      heatTolerant: true,
      companionPlants: ["beans"],
      commonPests: ["stem borer"],
      commonDiseases: ["downy mildew", "rust"]
    },
    {
      name: "Quinoa",
      scientificName: "Chenopodium quinoa",
      category: "CROPS",
      description: "High-protein pseudocereal superfood",
      climateZones: ["TEMPERATE", "ARID"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.5,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 4,
      daysToMaturity: 120,
      matureHeight: 6,
      droughtTolerant: true,
      companionPlants: ["beans"],
      commonPests: ["aphids", "leaf miners"],
      commonDiseases: ["downy mildew"]
    },
    {
      name: "Buckwheat",
      scientificName: "Fagopyrum esculentum",
      category: "CROPS",
      description: "Fast-growing pseudocereal for poor soils",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY", "LOAM"],
      soilPhMin: 5.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 4,
      rowSpacing: 6,
      germinationDays: 5,
      daysToMaturity: 80,
      matureHeight: 3,
      companionPlants: ["cabbage"],
      commonPests: ["aphids"],
      commonDiseases: ["root rot"]
    }
  ],

  // ==================== LEGUMES ====================
  legumes: [
    {
      name: "Green Bean",
      scientificName: "Phaseolus vulgaris",
      category: "VEGETABLES",
      description: "Popular fresh vegetable bean",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 6,
      rowSpacing: 24,
      germinationDays: 8,
      daysToMaturity: 55,
      matureHeight: 2,
      companionPlants: ["corn", "radish"],
      incompatibleWith: ["onion", "garlic"],
      commonPests: ["bean beetle", "aphids"],
      commonDiseases: ["bean rust", "mosaic virus"],
      varieties: [
        {
          name: "Bush Bean",
          description: "Compact variety needing no support",
          daysToMaturity: 50,
          yieldPerPlant: 0.5,
          yieldUnit: "lbs"
        },
        {
          name: "Pole Bean",
          description: "Climbing variety with extended harvest",
          daysToMaturity: 65,
          yieldPerPlant: 1,
          yieldUnit: "lbs"
        }
      ]
    },
    {
      name: "Pea",
      scientificName: "Pisum sativum",
      category: "VEGETABLES",
      description: "Cool-season legume for fresh or dried use",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 2,
      rowSpacing: 7,
      germinationDays: 10,
      daysToMaturity: 65,
      matureHeight: 3,
      companionPlants: ["carrot", "radish"],
      commonPests: ["pea weevil", "aphids"],
      commonDiseases: ["powdery mildew", "root rot"]
    },
    {
      name: "Lentil",
      scientificName: "Lens culinaris",
      category: "CROPS",
      description: "Protein-rich pulse crop",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 8,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 1,
      rowSpacing: 7,
      germinationDays: 10,
      daysToMaturity: 110,
      matureHeight: 1.5,
      droughtTolerant: true,
      companionPlants: ["grains"],
      commonPests: ["aphids", "thrips"],
      commonDiseases: ["ascochyta blight", "rust"]
    },
    {
      name: "Chickpea",
      scientificName: "Cicer arietinum",
      category: "CROPS",
      description: "Drought-tolerant pulse for dry regions",
      climateZones: ["MEDITERRANEAN", "ARID", "SUBTROPICAL"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 2,
      plantSpacing: 4,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 100,
      matureHeight: 2,
      droughtTolerant: true,
      companionPlants: ["grains"],
      commonPests: ["pod borer"],
      commonDiseases: ["ascochyta blight", "fusarium wilt"]
    },
    {
      name: "Black Bean",
      scientificName: "Phaseolus vulgaris",
      category: "CROPS",
      description: "High-protein dried bean variety",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1.5,
      plantSpacing: 6,
      rowSpacing: 30,
      germinationDays: 8,
      daysToMaturity: 90,
      matureHeight: 2,
      companionPlants: ["corn", "squash"],
      commonPests: ["bean beetle"],
      commonDiseases: ["anthracnose", "rust"]
    },
    {
      name: "Lima Bean",
      scientificName: "Phaseolus lunatus",
      category: "VEGETABLES",
      description: "Large flat bean for fresh or dried use",
      climateZones: ["SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1.5,
      plantSpacing: 8,
      rowSpacing: 36,
      germinationDays: 10,
      daysToMaturity: 75,
      matureHeight: 2,
      heatTolerant: true,
      companionPlants: ["corn"],
      commonPests: ["lima bean pod borer"],
      commonDiseases: ["downy mildew"]
    }
  ],

  // ==================== ROOT VEGETABLES ====================
  rootVegetables: [
    {
      name: "Radish",
      scientificName: "Raphanus sativus",
      category: "VEGETABLES",
      description: "Fast-growing crisp root vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 2,
      rowSpacing: 6,
      germinationDays: 5,
      daysToMaturity: 25,
      matureHeight: 0.5,
      companionPlants: ["lettuce", "peas"],
      commonPests: ["flea beetles"],
      commonDiseases: ["clubroot"]
    },
    {
      name: "Beet",
      scientificName: "Beta vulgaris",
      category: "VEGETABLES",
      description: "Sweet root vegetable with edible greens",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 3,
      rowSpacing: 12,
      germinationDays: 10,
      daysToMaturity: 60,
      matureHeight: 1,
      companionPlants: ["onion", "cabbage"],
      commonPests: ["leaf miners"],
      commonDiseases: ["cercospora leaf spot"]
    },
    {
      name: "Turnip",
      scientificName: "Brassica rapa",
      category: "VEGETABLES",
      description: "Cool-season root with edible greens",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 4,
      rowSpacing: 12,
      germinationDays: 7,
      daysToMaturity: 55,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["peas"],
      commonPests: ["flea beetles", "aphids"],
      commonDiseases: ["clubroot", "white spot"]
    },
    {
      name: "Parsnip",
      scientificName: "Pastinaca sativa",
      category: "VEGETABLES",
      description: "Sweet cold-hardy root vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 3,
      rowSpacing: 18,
      germinationDays: 21,
      daysToMaturity: 120,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["radish", "lettuce"],
      commonPests: ["carrot fly"],
      commonDiseases: ["canker"]
    },
    {
      name: "Sweet Potato",
      scientificName: "Ipomoea batatas",
      category: "VEGETABLES",
      description: "Tropical root vegetable high in vitamins",
      climateZones: ["SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 8,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 4,
      plantSpacing: 12,
      rowSpacing: 36,
      germinationDays: 14,
      daysToMaturity: 120,
      matureHeight: 1,
      heatTolerant: true,
      companionPlants: ["oregano", "parsley"],
      commonPests: ["sweet potato weevil"],
      commonDiseases: ["black rot", "scurf"]
    },
    {
      name: "Rutabaga",
      scientificName: "Brassica napobrassica",
      category: "VEGETABLES",
      description: "Large sweet root vegetable for storage",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 18,
      germinationDays: 10,
      daysToMaturity: 90,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["onion", "peas"],
      commonPests: ["flea beetles"],
      commonDiseases: ["clubroot"]
    }
  ],

  // ==================== LEAFY GREENS ====================
  leafyGreens: [
    {
      name: "Kale",
      scientificName: "Brassica oleracea var. sabellica",
      category: "VEGETABLES",
      description: "Nutrient-dense cold-hardy green",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 7,
      daysToMaturity: 60,
      matureHeight: 2,
      coldTolerant: true,
      companionPlants: ["beets", "onions"],
      commonPests: ["cabbage worm", "aphids"],
      commonDiseases: ["black rot", "clubroot"]
    },
    {
      name: "Swiss Chard",
      scientificName: "Beta vulgaris var. cicla",
      category: "VEGETABLES",
      description: "Colorful nutritious leafy green",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 18,
      germinationDays: 10,
      daysToMaturity: 55,
      matureHeight: 1.5,
      heatTolerant: true,
      companionPlants: ["beans", "cabbage"],
      commonPests: ["leaf miners"],
      commonDiseases: ["cercospora leaf spot"]
    },
    {
      name: "Collard Greens",
      scientificName: "Brassica oleracea var. acephala",
      category: "VEGETABLES",
      description: "Heat-tolerant southern green",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 18,
      rowSpacing: 30,
      germinationDays: 8,
      daysToMaturity: 75,
      matureHeight: 2,
      heatTolerant: true,
      coldTolerant: true,
      companionPlants: ["tomato", "onion"],
      commonPests: ["cabbage worm"],
      commonDiseases: ["black rot"]
    },
    {
      name: "Arugula",
      scientificName: "Eruca sativa",
      category: "VEGETABLES",
      description: "Peppery salad green",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 4,
      rowSpacing: 12,
      germinationDays: 5,
      daysToMaturity: 40,
      matureHeight: 0.5,
      companionPlants: ["bush beans", "beets"],
      commonPests: ["flea beetles"],
      commonDiseases: ["downy mildew"]
    },
    {
      name: "Mustard Greens",
      scientificName: "Brassica juncea",
      category: "VEGETABLES",
      description: "Spicy fast-growing green",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 5,
      daysToMaturity: 45,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["beans", "onion"],
      commonPests: ["aphids", "flea beetles"],
      commonDiseases: ["white rust"]
    },
    {
      name: "Bok Choy",
      scientificName: "Brassica rapa var. chinensis",
      category: "VEGETABLES",
      description: "Asian green with crisp stalks",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 6,
      rowSpacing: 18,
      germinationDays: 7,
      daysToMaturity: 50,
      matureHeight: 1,
      companionPlants: ["beets", "bush beans"],
      commonPests: ["cabbage worm", "aphids"],
      commonDiseases: ["clubroot"]
    }
  ],

  // ==================== VINE CROPS ====================
  vineCrops: [
    {
      name: "Cucumber",
      scientificName: "Cucumis sativus",
      category: "VEGETABLES",
      description: "Refreshing vine crop for fresh eating",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 36,
      rowSpacing: 60,
      germinationDays: 7,
      daysToMaturity: 60,
      matureHeight: 1,
      matureSpread: 6,
      companionPlants: ["beans", "peas", "radish"],
      incompatibleWith: ["aromatic herbs"],
      commonPests: ["cucumber beetle", "aphids"],
      commonDiseases: ["powdery mildew", "bacterial wilt"]
    },
    {
      name: "Watermelon",
      scientificName: "Citrullus lanatus",
      category: "FRUITS",
      description: "Large sweet summer fruit",
      climateZones: ["SUBTROPICAL", "TROPICAL", "TEMPERATE"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 60,
      rowSpacing: 72,
      germinationDays: 10,
      daysToMaturity: 90,
      matureHeight: 1,
      matureSpread: 10,
      heatTolerant: true,
      companionPlants: ["radish", "nasturtium"],
      commonPests: ["aphids", "spider mites"],
      commonDiseases: ["anthracnose", "fusarium wilt"]
    },
    {
      name: "Cantaloupe",
      scientificName: "Cucumis melo",
      category: "FRUITS",
      description: "Sweet orange-fleshed melon",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 36,
      rowSpacing: 60,
      germinationDays: 8,
      daysToMaturity: 85,
      matureHeight: 1,
      matureSpread: 6,
      companionPlants: ["corn", "radish"],
      commonPests: ["cucumber beetle"],
      commonDiseases: ["powdery mildew"]
    },
    {
      name: "Zucchini",
      scientificName: "Cucurbita pepo",
      category: "VEGETABLES",
      description: "Prolific summer squash",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 36,
      rowSpacing: 48,
      germinationDays: 7,
      daysToMaturity: 50,
      matureHeight: 2,
      matureSpread: 4,
      companionPlants: ["nasturtium", "radish"],
      commonPests: ["squash bug", "vine borer"],
      commonDiseases: ["powdery mildew", "blossom end rot"]
    },
    {
      name: "Pumpkin",
      scientificName: "Cucurbita pepo",
      category: "VEGETABLES",
      description: "Large autumn squash for decoration and eating",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 60,
      rowSpacing: 96,
      germinationDays: 10,
      daysToMaturity: 110,
      matureHeight: 2,
      matureSpread: 15,
      companionPlants: ["corn", "radish"],
      commonPests: ["squash bug", "cucumber beetle"],
      commonDiseases: ["powdery mildew", "black rot"]
    },
    {
      name: "Butternut Squash",
      scientificName: "Cucurbita moschata",
      category: "VEGETABLES",
      description: "Sweet winter squash with long storage",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 48,
      rowSpacing: 72,
      germinationDays: 10,
      daysToMaturity: 100,
      matureHeight: 1,
      matureSpread: 8,
      companionPlants: ["beans", "mint"],
      commonPests: ["squash vine borer"],
      commonDiseases: ["powdery mildew"]
    }
  ],

  // ==================== TROPICAL FRUITS ====================
  tropicalFruits: [
    {
      name: "Banana",
      scientificName: "Musa acuminata",
      category: "FRUITS",
      description: "Tropical staple fruit high in potassium",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 120,
      daysToMaturity: 365,
      matureHeight: 15,
      matureSpread: 10,
      companionPlants: ["sweet potato", "lemongrass"],
      commonPests: ["banana weevil", "nematodes"],
      commonDiseases: ["panama disease", "black sigatoka"]
    },
    {
      name: "Mango",
      scientificName: "Mangifera indica",
      category: "FRUITS",
      description: "King of tropical fruits with sweet flesh",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 10,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 360,
      daysToMaturity: 2190, // ~6 years
      matureHeight: 60,
      matureSpread: 50,
      droughtTolerant: true,
      companionPlants: ["citrus", "guava"],
      commonPests: ["mango hopper", "fruit fly"],
      commonDiseases: ["anthracnose", "powdery mildew"]
    },
    {
      name: "Pineapple",
      scientificName: "Ananas comosus",
      category: "FRUITS",
      description: "Tropical fruit with enzyme-rich flesh",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 10,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 4.5,
      soilPhMax: 6.5,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 2,
      plantSpacing: 24,
      rowSpacing: 36,
      daysToMaturity: 540,
      matureHeight: 3,
      matureSpread: 3,
      droughtTolerant: true,
      companionPlants: ["coffee", "pepper"],
      commonPests: ["mealybugs", "scale"],
      commonDiseases: ["heart rot", "root rot"]
    },
    {
      name: "Papaya",
      scientificName: "Carica papaya",
      category: "FRUITS",
      description: "Fast-growing tropical fruit with digestive enzymes",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 10,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 120,
      daysToMaturity: 270,
      matureHeight: 20,
      matureSpread: 10,
      companionPlants: ["beans", "sweet potato"],
      commonPests: ["papaya fruit fly", "spider mites"],
      commonDiseases: ["papaya ringspot virus", "anthracnose"]
    },
    {
      name: "Avocado",
      scientificName: "Persea americana",
      category: "FRUITS",
      description: "Nutrient-dense fruit with healthy fats",
      climateZones: ["SUBTROPICAL", "MEDITERRANEAN"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 240,
      daysToMaturity: 1095,
      matureHeight: 40,
      matureSpread: 30,
      companionPlants: ["citrus", "coffee"],
      commonPests: ["thrips", "lace bugs"],
      commonDiseases: ["root rot", "anthracnose"]
    },
    {
      name: "Passion Fruit",
      scientificName: "Passiflora edulis",
      category: "FRUITS",
      description: "Aromatic tropical vine fruit",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 120,
      rowSpacing: 180,
      daysToMaturity: 540,
      matureHeight: 15,
      matureSpread: 15,
      companionPlants: ["beans", "lettuce"],
      commonPests: ["fruit fly", "aphids"],
      commonDiseases: ["fusarium wilt", "woodiness virus"]
    }
  ],

  // ==================== BERRIES ====================
  berries: [
    {
      name: "Raspberry",
      scientificName: "Rubus idaeus",
      category: "FRUITS",
      description: "Sweet-tart summer berry",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 24,
      rowSpacing: 96,
      daysToMaturity: 365,
      matureHeight: 6,
      matureSpread: 3,
      companionPlants: ["garlic", "tansy"],
      commonPests: ["japanese beetle", "spider mites"],
      commonDiseases: ["anthracnose", "root rot"]
    },
    {
      name: "Blackberry",
      scientificName: "Rubus fruticosus",
      category: "FRUITS",
      description: "Hardy bramble fruit",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 36,
      rowSpacing: 120,
      daysToMaturity: 365,
      matureHeight: 8,
      matureSpread: 4,
      droughtTolerant: true,
      companionPlants: ["mint", "lemon balm"],
      commonPests: ["spotted wing drosophila"],
      commonDiseases: ["orange rust", "anthracnose"]
    },
    {
      name: "Cranberry",
      scientificName: "Vaccinium macrocarpon",
      category: "FRUITS",
      description: "Tart bog berry high in antioxidants",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 7,
      soilTypes: ["PEAT", "SANDY"],
      soilPhMin: 4.0,
      soilPhMax: 5.5,
      waterRequirement: "VERY_HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 12,
      rowSpacing: 24,
      daysToMaturity: 1095,
      matureHeight: 0.5,
      matureSpread: 2,
      coldTolerant: true,
      companionPlants: ["azalea"],
      commonPests: ["cranberry fruitworm"],
      commonDiseases: ["fruit rot", "leaf spot"]
    },
    {
      name: "Gooseberry",
      scientificName: "Ribes uva-crispa",
      category: "FRUITS",
      description: "Tart berry for fresh eating and preserves",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 48,
      rowSpacing: 96,
      daysToMaturity: 730,
      matureHeight: 5,
      matureSpread: 5,
      coldTolerant: true,
      companionPlants: ["tomato", "chives"],
      commonPests: ["gooseberry sawfly"],
      commonDiseases: ["powdery mildew", "leaf spot"]
    }
  ],

  // ==================== ALLIUMS ====================
  alliums: [
    {
      name: "Garlic",
      scientificName: "Allium sativum",
      category: "VEGETABLES",
      description: "Pungent bulb with medicinal properties",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 2,
      plantSpacing: 4,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 240,
      matureHeight: 2,
      companionPlants: ["roses", "fruit trees"],
      incompatibleWith: ["beans", "peas"],
      commonPests: ["onion maggot"],
      commonDiseases: ["white rot", "rust"]
    },
    {
      name: "Leek",
      scientificName: "Allium ampeloprasum",
      category: "VEGETABLES",
      description: "Mild onion-like vegetable with thick stems",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 120,
      matureHeight: 2,
      coldTolerant: true,
      companionPlants: ["carrot", "celery"],
      commonPests: ["onion fly", "thrips"],
      commonDiseases: ["rust", "white tip"]
    },
    {
      name: "Shallot",
      scientificName: "Allium cepa var. aggregatum",
      category: "VEGETABLES",
      description: "Mild gourmet onion variety",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 10,
      daysToMaturity: 100,
      matureHeight: 1,
      companionPlants: ["beets", "lettuce"],
      commonPests: ["thrips"],
      commonDiseases: ["neck rot", "downy mildew"]
    },
    {
      name: "Chives",
      scientificName: "Allium schoenoprasum",
      category: "HERBS",
      description: "Mild onion-flavored herb",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 60,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["carrots", "tomatoes"],
      commonPests: ["thrips"],
      commonDiseases: ["rust"]
    }
  ],

  // ==================== BRASSICAS ====================
  brassicas: [
    {
      name: "Cabbage",
      scientificName: "Brassica oleracea var. capitata",
      category: "VEGETABLES",
      description: "Dense leafy head vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 18,
      rowSpacing: 24,
      germinationDays: 7,
      daysToMaturity: 80,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["dill", "onion"],
      incompatibleWith: ["strawberry"],
      commonPests: ["cabbage worm", "aphids"],
      commonDiseases: ["clubroot", "black rot"]
    },
    {
      name: "Cauliflower",
      scientificName: "Brassica oleracea var. botrytis",
      category: "VEGETABLES",
      description: "White flowering head vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 18,
      rowSpacing: 30,
      germinationDays: 8,
      daysToMaturity: 75,
      matureHeight: 2,
      companionPlants: ["celery", "onion"],
      commonPests: ["cabbage worm"],
      commonDiseases: ["downy mildew", "black rot"]
    },
    {
      name: "Brussels Sprouts",
      scientificName: "Brassica oleracea var. gemmifera",
      category: "VEGETABLES",
      description: "Mini cabbage-like vegetable on stalks",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 24,
      rowSpacing: 30,
      germinationDays: 7,
      daysToMaturity: 100,
      matureHeight: 3,
      coldTolerant: true,
      companionPlants: ["beets", "carrots"],
      commonPests: ["aphids", "cabbage worm"],
      commonDiseases: ["clubroot", "powdery mildew"]
    }
  ],

  // ==================== NIGHTSHADES ====================
  nightshades: [
    {
      name: "Eggplant",
      scientificName: "Solanum melongena",
      category: "VEGETABLES",
      description: "Purple glossy fruit vegetable",
      climateZones: ["SUBTROPICAL", "TROPICAL", "MEDITERRANEAN"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 24,
      rowSpacing: 36,
      germinationDays: 14,
      daysToMaturity: 80,
      matureHeight: 3,
      heatTolerant: true,
      companionPlants: ["beans", "pepper"],
      commonPests: ["flea beetles", "aphids"],
      commonDiseases: ["verticillium wilt", "bacterial wilt"]
    },
    {
      name: "Tomatillo",
      scientificName: "Physalis philadelphica",
      category: "VEGETABLES",
      description: "Husked green fruit for Mexican cuisine",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 36,
      rowSpacing: 48,
      germinationDays: 10,
      daysToMaturity: 75,
      matureHeight: 4,
      companionPlants: ["basil", "parsley"],
      commonPests: ["tomato hornworm"],
      commonDiseases: ["early blight"]
    },
    {
      name: "Hot Pepper",
      scientificName: "Capsicum chinense",
      category: "VEGETABLES",
      description: "Spicy pepper varieties including habanero",
      climateZones: ["SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 18,
      rowSpacing: 24,
      germinationDays: 14,
      daysToMaturity: 90,
      matureHeight: 3,
      heatTolerant: true,
      companionPlants: ["basil", "oregano"],
      commonPests: ["aphids", "pepper weevil"],
      commonDiseases: ["bacterial spot", "mosaic virus"]
    }
  ],

  // ==================== STONE FRUITS ====================
  stoneFruits: [
    {
      name: "Peach",
      scientificName: "Prunus persica",
      category: "FRUITS",
      description: "Sweet juicy stone fruit",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 9,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 240,
      daysToMaturity: 1095,
      matureHeight: 25,
      matureSpread: 25,
      companionPlants: ["basil", "tansy"],
      commonPests: ["peach tree borer", "oriental fruit moth"],
      commonDiseases: ["brown rot", "leaf curl"]
    },
    {
      name: "Plum",
      scientificName: "Prunus domestica",
      category: "FRUITS",
      description: "Sweet-tart stone fruit",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 240,
      daysToMaturity: 1095,
      matureHeight: 20,
      matureSpread: 20,
      companionPlants: ["chives", "comfrey"],
      commonPests: ["plum curculio", "aphids"],
      commonDiseases: ["brown rot", "bacterial spot"]
    },
    {
      name: "Apricot",
      scientificName: "Prunus armeniaca",
      category: "FRUITS",
      description: "Early season orange stone fruit",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 8,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 240,
      daysToMaturity: 1095,
      matureHeight: 20,
      matureSpread: 20,
      droughtTolerant: true,
      companionPlants: ["basil", "tansy"],
      commonPests: ["oriental fruit moth"],
      commonDiseases: ["brown rot", "bacterial canker"]
    }
  ],

  // ==================== CITRUS FRUITS ====================
  citrusFruits: [
    {
      name: "Lemon",
      scientificName: "Citrus limon",
      category: "FRUITS",
      description: "Acidic citrus fruit for culinary use",
      climateZones: ["MEDITERRANEAN", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 240,
      daysToMaturity: 1095,
      matureHeight: 20,
      matureSpread: 20,
      companionPlants: ["herbs", "vegetables"],
      commonPests: ["citrus psyllid", "scale"],
      commonDiseases: ["citrus canker", "root rot"]
    },
    {
      name: "Lime",
      scientificName: "Citrus aurantifolia",
      category: "FRUITS",
      description: "Small acidic green citrus",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 10,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 180,
      daysToMaturity: 1095,
      matureHeight: 15,
      matureSpread: 15,
      companionPlants: ["ginger", "turmeric"],
      commonPests: ["citrus psyllid", "mites"],
      commonDiseases: ["citrus canker", "melanose"]
    },
    {
      name: "Grapefruit",
      scientificName: "Citrus paradisi",
      category: "FRUITS",
      description: "Large tart citrus fruit",
      climateZones: ["SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 300,
      daysToMaturity: 1460,
      matureHeight: 25,
      matureSpread: 25,
      companionPlants: ["rosemary", "lavender"],
      commonPests: ["citrus psyllid"],
      commonDiseases: ["citrus canker", "greening"]
    }
  ],

  // ==================== SPICES & CULINARY HERBS ====================
  spicesHerbs: [
    {
      name: "Cilantro",
      scientificName: "Coriandrum sativum",
      category: "HERBS",
      description: "Fresh herb for Mexican and Asian cuisine",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 10,
      daysToMaturity: 50,
      matureHeight: 2,
      companionPlants: ["tomato", "spinach"],
      commonPests: ["aphids"],
      commonDiseases: ["bacterial leaf spot"]
    },
    {
      name: "Parsley",
      scientificName: "Petroselinum crispum",
      category: "HERBS",
      description: "Versatile culinary herb rich in vitamins",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 8,
      rowSpacing: 12,
      germinationDays: 21,
      daysToMaturity: 70,
      matureHeight: 1,
      companionPlants: ["tomato", "carrot"],
      commonPests: ["aphids", "carrot fly"],
      commonDiseases: ["leaf spot"]
    },
    {
      name: "Rosemary",
      scientificName: "Rosmarinus officinalis",
      category: "HERBS",
      description: "Woody Mediterranean herb",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 7,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "VERY_LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 24,
      rowSpacing: 36,
      daysToMaturity: 90,
      matureHeight: 4,
      matureSpread: 3,
      droughtTolerant: true,
      companionPlants: ["cabbage", "beans"],
      commonPests: ["spider mites"],
      commonDiseases: ["root rot"]
    },
    {
      name: "Mint",
      scientificName: "Mentha spicata",
      category: "HERBS",
      description: "Aromatic herb for teas and cooking",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 18,
      rowSpacing: 24,
      daysToMaturity: 60,
      matureHeight: 2,
      matureSpread: 3,
      companionPlants: ["cabbage", "tomato"],
      commonPests: ["aphids", "spider mites"],
      commonDiseases: ["rust", "powdery mildew"]
    },
    {
      name: "Sage",
      scientificName: "Salvia officinalis",
      category: "HERBS",
      description: "Silvery herb for seasoning and medicine",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 18,
      rowSpacing: 24,
      daysToMaturity: 75,
      matureHeight: 2,
      matureSpread: 2,
      droughtTolerant: true,
      companionPlants: ["brassicas", "carrots"],
      commonPests: ["aphids"],
      commonDiseases: ["root rot"]
    },
    {
      name: "Dill",
      scientificName: "Anethum graveolens",
      category: "HERBS",
      description: "Feathery herb for pickles and fish",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 10,
      daysToMaturity: 70,
      matureHeight: 3,
      companionPlants: ["cabbage", "lettuce"],
      incompatibleWith: ["carrot"],
      commonPests: ["aphids"],
      commonDiseases: ["damping off"]
    }
  ],

  // ==================== SPECIALTY CROPS ====================
  specialtyCrops: [
    {
      name: "Sunflower",
      scientificName: "Helianthus annuus",
      category: "CROPS",
      description: "Oil seed crop with edible seeds",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 24,
      rowSpacing: 36,
      germinationDays: 10,
      daysToMaturity: 120,
      matureHeight: 8,
      droughtTolerant: true,
      companionPlants: ["beans", "squash"],
      incompatibleWith: ["potato"],
      commonPests: ["sunflower moth", "birds"],
      commonDiseases: ["downy mildew", "rust"]
    },
    {
      name: "Cotton",
      scientificName: "Gossypium hirsutum",
      category: "CROPS",
      description: "Fiber crop for textile production",
      climateZones: ["SUBTROPICAL", "TEMPERATE"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "CLAY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 8.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 6,
      rowSpacing: 40,
      germinationDays: 7,
      daysToMaturity: 200,
      matureHeight: 5,
      heatTolerant: true,
      droughtTolerant: true,
      companionPlants: ["legumes"],
      commonPests: ["bollworm", "aphids"],
      commonDiseases: ["fusarium wilt", "verticillium wilt"]
    },
    {
      name: "Flax",
      scientificName: "Linum usitatissimum",
      category: "CROPS",
      description: "Fiber and oil seed crop",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 7,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 7,
      germinationDays: 10,
      daysToMaturity: 120,
      matureHeight: 4,
      coldTolerant: true,
      companionPlants: ["carrots", "potatoes"],
      commonPests: ["flea beetles"],
      commonDiseases: ["rust", "wilt"]
    },
    {
      name: "Hemp",
      scientificName: "Cannabis sativa",
      category: "CROPS",
      description: "Industrial fiber and oil crop",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.75,
      plantSpacing: 24,
      rowSpacing: 36,
      germinationDays: 7,
      daysToMaturity: 120,
      matureHeight: 12,
      droughtTolerant: true,
      commonPests: ["hemp flea beetle"],
      commonDiseases: ["gray mold", "damping off"]
    },
    {
      name: "Canola",
      scientificName: "Brassica napus",
      category: "CROPS",
      description: "Oil seed crop for cooking oil production",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 7,
      germinationDays: 7,
      daysToMaturity: 100,
      matureHeight: 5,
      coldTolerant: true,
      companionPlants: ["wheat", "barley"],
      commonPests: ["flea beetles", "aphids"],
      commonDiseases: ["blackleg", "sclerotinia"]
    },
    {
      name: "Safflower",
      scientificName: "Carthamus tinctorius",
      category: "CROPS",
      description: "Oil seed crop for high-oleic cooking oil",
      climateZones: ["ARID", "TEMPERATE"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 6,
      rowSpacing: 24,
      germinationDays: 10,
      daysToMaturity: 120,
      matureHeight: 4,
      droughtTolerant: true,
      heatTolerant: true,
      companionPlants: ["sorghum"],
      commonPests: ["aphids", "thrips"],
      commonDiseases: ["rust", "alternaria"]
    },
    {
      name: "Sesame",
      scientificName: "Sesamum indicum",
      category: "CROPS",
      description: "Small oil seed crop for tahini and oil",
      climateZones: ["SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 7,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 18,
      germinationDays: 7,
      daysToMaturity: 90,
      matureHeight: 3,
      droughtTolerant: true,
      heatTolerant: true,
      companionPlants: ["cotton", "sorghum"],
      commonPests: ["aphids", "capsule borer"],
      commonDiseases: ["charcoal rot", "phyllody"]
    },
    {
      name: "Alfalfa",
      scientificName: "Medicago sativa",
      category: "CROPS",
      description: "Nitrogen-fixing forage crop",
      climateZones: ["TEMPERATE", "ARID"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.5,
      soilPhMax: 8.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 8,
      germinationDays: 7,
      daysToMaturity: 60,
      matureHeight: 3,
      droughtTolerant: true,
      companionPlants: ["grasses"],
      commonPests: ["alfalfa weevil", "aphids"],
      commonDiseases: ["bacterial wilt", "anthracnose"]
    },
    {
      name: "Clover",
      scientificName: "Trifolium pratense",
      category: "CROPS",
      description: "Nitrogen-fixing cover crop and forage",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 6,
      germinationDays: 7,
      daysToMaturity: 60,
      matureHeight: 2,
      companionPlants: ["grasses", "fruit trees"],
      commonPests: ["aphids"],
      commonDiseases: ["powdery mildew"]
    },
    {
      name: "Timothy Grass",
      scientificName: "Phleum pratense",
      category: "CROPS",
      description: "Premium hay and forage grass",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 4,
      germinationDays: 10,
      daysToMaturity: 75,
      matureHeight: 4,
      coldTolerant: true,
      companionPlants: ["clover", "alfalfa"],
      commonPests: ["armyworm"],
      commonDiseases: ["rust", "leaf spot"]
    },
    {
      name: "Sugar Beet",
      scientificName: "Beta vulgaris",
      category: "CROPS",
      description: "Industrial crop for sugar production",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 1,
      plantSpacing: 6,
      rowSpacing: 22,
      germinationDays: 10,
      daysToMaturity: 170,
      matureHeight: 1,
      companionPlants: ["onion", "lettuce"],
      commonPests: ["sugar beet root maggot"],
      commonDiseases: ["cercospora leaf spot", "rhizoctonia"]
    },
    {
      name: "Sugar Cane",
      scientificName: "Saccharum officinarum",
      category: "CROPS",
      description: "Tropical crop for sugar and ethanol",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 60,
      rowSpacing: 60,
      daysToMaturity: 365,
      matureHeight: 12,
      heatTolerant: true,
      companionPlants: ["legumes"],
      commonPests: ["sugarcane borer", "aphids"],
      commonDiseases: ["smut", "mosaic virus"]
    },
    {
      name: "Tobacco",
      scientificName: "Nicotiana tabacum",
      category: "CROPS",
      description: "Commercial leaf crop",
      climateZones: ["SUBTROPICAL", "TEMPERATE"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.125,
      plantSpacing: 24,
      rowSpacing: 42,
      germinationDays: 10,
      daysToMaturity: 120,
      matureHeight: 6,
      heatTolerant: true,
      companionPlants: ["marigold"],
      commonPests: ["hornworm", "aphids"],
      commonDiseases: ["mosaic virus", "black shank"]
    },
    {
      name: "Hops",
      scientificName: "Humulus lupulus",
      category: "CROPS",
      description: "Climbing crop for beer brewing",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 84,
      rowSpacing: 168,
      daysToMaturity: 120,
      matureHeight: 20,
      companionPlants: ["corn", "beans"],
      commonPests: ["spider mites", "aphids"],
      commonDiseases: ["downy mildew", "powdery mildew"]
    },
    {
      name: "Coffee",
      scientificName: "Coffea arabica",
      category: "CROPS",
      description: "Tropical beverage crop",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 10,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 120,
      daysToMaturity: 1095,
      matureHeight: 15,
      matureSpread: 10,
      companionPlants: ["banana", "shade trees"],
      commonPests: ["coffee berry borer"],
      commonDiseases: ["coffee rust", "anthracnose"]
    },
    {
      name: "Tea",
      scientificName: "Camellia sinensis",
      category: "CROPS",
      description: "Beverage crop for tea production",
      climateZones: ["SUBTROPICAL", "TEMPERATE"],
      hardinessZoneMin: 7,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 4.5,
      soilPhMax: 6.0,
      waterRequirement: "HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 60,
      rowSpacing: 120,
      daysToMaturity: 1095,
      matureHeight: 6,
      matureSpread: 4,
      companionPlants: ["shade trees"],
      commonPests: ["tea mosquito bug"],
      commonDiseases: ["blister blight", "gray blight"]
    },
    {
      name: "Peanut",
      scientificName: "Arachis hypogaea",
      category: "CROPS",
      description: "Underground legume nut crop",
      climateZones: ["SUBTROPICAL", "TEMPERATE"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 5.8,
      soilPhMax: 6.2,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1.5,
      plantSpacing: 6,
      rowSpacing: 30,
      germinationDays: 10,
      daysToMaturity: 120,
      matureHeight: 1.5,
      heatTolerant: true,
      companionPlants: ["corn", "squash"],
      commonPests: ["thrips", "aphids"],
      commonDiseases: ["leaf spot", "stem rot"]
    },
    {
      name: "Mustard Seed",
      scientificName: "Brassica nigra",
      category: "CROPS",
      description: "Spice crop for mustard production",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 7,
      daysToMaturity: 85,
      matureHeight: 3,
      coldTolerant: true,
      companionPlants: ["grains"],
      commonPests: ["flea beetles"],
      commonDiseases: ["white rust", "downy mildew"]
    },
    {
      name: "Chia",
      scientificName: "Salvia hispanica",
      category: "CROPS",
      description: "Superfood seed crop high in omega-3",
      climateZones: ["SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 8,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 18,
      rowSpacing: 24,
      germinationDays: 7,
      daysToMaturity: 120,
      matureHeight: 4,
      droughtTolerant: true,
      companionPlants: ["corn", "beans"],
      commonPests: ["aphids"],
      commonDiseases: ["damping off"]
    },
    {
      name: "Amaranth",
      scientificName: "Amaranthus cruentus",
      category: "CROPS",
      description: "Nutritious pseudocereal grain",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 7,
      daysToMaturity: 110,
      matureHeight: 6,
      droughtTolerant: true,
      heatTolerant: true,
      companionPlants: ["beans", "corn"],
      commonPests: ["aphids", "flea beetles"],
      commonDiseases: ["root rot"]
    }
  ],

  // ==================== MEDICINAL PLANTS ====================
  medicinalPlants: [
    {
      name: "Echinacea",
      scientificName: "Echinacea purpurea",
      category: "HERBS",
      description: "Immune-boosting medicinal herb",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 18,
      rowSpacing: 24,
      daysToMaturity: 120,
      matureHeight: 3,
      droughtTolerant: true,
      companionPlants: ["bee balm", "black-eyed susan"],
      commonPests: ["aphids"],
      commonDiseases: ["aster yellows"]
    },
    {
      name: "Lavender",
      scientificName: "Lavandula angustifolia",
      category: "HERBS",
      description: "Aromatic herb for relaxation and crafts",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 5,
      hardinessZoneMax: 9,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 6.5,
      soilPhMax: 8.0,
      waterRequirement: "VERY_LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 24,
      rowSpacing: 36,
      daysToMaturity: 120,
      matureHeight: 3,
      matureSpread: 3,
      droughtTolerant: true,
      companionPlants: ["roses", "fruit trees"],
      commonPests: ["spittlebugs"],
      commonDiseases: ["root rot", "leaf spot"]
    },
    {
      name: "Chamomile",
      scientificName: "Matricaria chamomilla",
      category: "HERBS",
      description: "Calming herb for teas and medicine",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["SANDY", "LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.5,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.125,
      plantSpacing: 8,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 65,
      matureHeight: 2,
      droughtTolerant: true,
      companionPlants: ["cabbage", "onion"],
      commonPests: ["aphids"],
      commonDiseases: ["damping off"]
    }
  ],

  // ==================== SQUASH FAMILY ====================
  squashFamily: [
    {
      name: "Acorn Squash",
      scientificName: "Cucurbita pepo",
      category: "VEGETABLES",
      description: "Ribbed winter squash with sweet flesh",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 48,
      rowSpacing: 72,
      germinationDays: 10,
      daysToMaturity: 110,
      matureHeight: 1,
      matureSpread: 8,
      companionPlants: ["beans", "corn"],
      commonPests: ["squash bug", "vine borer"],
      commonDiseases: ["powdery mildew"]
    },
    {
      name: "Delicata Squash",
      scientificName: "Cucurbita pepo",
      category: "VEGETABLES",
      description: "Cream-colored striped winter squash",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 36,
      rowSpacing: 72,
      germinationDays: 8,
      daysToMaturity: 100,
      matureHeight: 1,
      matureSpread: 6,
      companionPlants: ["radish", "nasturtium"],
      commonPests: ["squash bug"],
      commonDiseases: ["powdery mildew"]
    }
  ],

  // ==================== ADDITIONAL VEGETABLES ====================
  additionalVegetables: [
    {
      name: "Celery",
      scientificName: "Apium graveolens",
      category: "VEGETABLES",
      description: "Crisp stalked vegetable for fresh eating",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.125,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 120,
      matureHeight: 2,
      companionPlants: ["cabbage", "leek"],
      commonPests: ["celery worm", "aphids"],
      commonDiseases: ["leaf blight", "heart rot"]
    },
    {
      name: "Asparagus",
      scientificName: "Asparagus officinalis",
      category: "VEGETABLES",
      description: "Perennial spring vegetable spears",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.5,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 6,
      plantSpacing: 18,
      rowSpacing: 60,
      daysToMaturity: 730, // 2 years to harvest
      matureHeight: 6,
      companionPlants: ["tomato", "parsley"],
      commonPests: ["asparagus beetle"],
      commonDiseases: ["fusarium wilt", "rust"]
    },
    {
      name: "Artichoke",
      scientificName: "Cynara cardunculus",
      category: "VEGETABLES",
      description: "Mediterranean thistle vegetable",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 7,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 36,
      rowSpacing: 48,
      daysToMaturity: 180,
      matureHeight: 4,
      matureSpread: 4,
      companionPlants: ["tarragon"],
      commonPests: ["aphids", "artichoke plume moth"],
      commonDiseases: ["gray mold", "crown rot"]
    },
    {
      name: "Okra",
      scientificName: "Abelmoschus esculentus",
      category: "VEGETABLES",
      description: "Heat-loving pod vegetable",
      climateZones: ["SUBTROPICAL", "TROPICAL"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 18,
      rowSpacing: 36,
      germinationDays: 10,
      daysToMaturity: 60,
      matureHeight: 6,
      heatTolerant: true,
      droughtTolerant: true,
      companionPlants: ["pepper", "eggplant"],
      commonPests: ["aphids", "corn earworm"],
      commonDiseases: ["verticillium wilt", "powdery mildew"]
    },
    {
      name: "Kohlrabi",
      scientificName: "Brassica oleracea var. gongylodes",
      category: "VEGETABLES",
      description: "Bulbous stem vegetable in cabbage family",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 7,
      daysToMaturity: 60,
      matureHeight: 1.5,
      coldTolerant: true,
      companionPlants: ["beets", "onion"],
      commonPests: ["cabbage worm", "flea beetles"],
      commonDiseases: ["clubroot", "black rot"]
    },
    {
      name: "Fennel",
      scientificName: "Foeniculum vulgare",
      category: "VEGETABLES",
      description: "Anise-flavored bulb vegetable",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 14,
      daysToMaturity: 90,
      matureHeight: 5,
      droughtTolerant: true,
      companionPlants: ["dill", "coriander"],
      incompatibleWith: ["tomato", "bean"],
      commonPests: ["aphids", "swallowtail caterpillar"],
      commonDiseases: ["bacterial blight"]
    },
    {
      name: "Endive",
      scientificName: "Cichorium endivia",
      category: "VEGETABLES",
      description: "Bitter leafy green for salads",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 8,
      rowSpacing: 12,
      germinationDays: 10,
      daysToMaturity: 65,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["carrot", "radish"],
      commonPests: ["aphids", "slugs"],
      commonDiseases: ["bottom rot", "downy mildew"]
    },
    {
      name: "Radicchio",
      scientificName: "Cichorium intybus",
      category: "VEGETABLES",
      description: "Red bitter leafy vegetable",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 8,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 75,
      matureHeight: 1,
      coldTolerant: true,
      companionPlants: ["onion", "carrot"],
      commonPests: ["aphids"],
      commonDiseases: ["soft rot"]
    },
    {
      name: "Watercress",
      scientificName: "Nasturtium officinale",
      category: "VEGETABLES",
      description: "Peppery aquatic green",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["CLAY", "SILT"],
      soilPhMin: 6.5,
      soilPhMax: 7.5,
      waterRequirement: "VERY_HIGH",
      sunRequirement: "PARTIAL_SHADE",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.125,
      plantSpacing: 4,
      rowSpacing: 6,
      germinationDays: 10,
      daysToMaturity: 40,
      matureHeight: 0.5,
      companionPlants: ["mint"],
      commonPests: ["aphids"],
      commonDiseases: ["bacterial soft rot"]
    },
    {
      name: "Celeriac",
      scientificName: "Apium graveolens var. rapaceum",
      category: "VEGETABLES",
      description: "Celery root vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.125,
      plantSpacing: 8,
      rowSpacing: 18,
      germinationDays: 21,
      daysToMaturity: 120,
      matureHeight: 1.5,
      coldTolerant: true,
      companionPlants: ["leek", "cabbage"],
      commonPests: ["carrot fly", "celery fly"],
      commonDiseases: ["leaf blight"]
    },
    {
      name: "Napa Cabbage",
      scientificName: "Brassica rapa var. pekinensis",
      category: "VEGETABLES",
      description: "Asian cabbage with tender leaves",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 7,
      daysToMaturity: 70,
      matureHeight: 1.5,
      companionPlants: ["beets", "onion"],
      commonPests: ["cabbage worm", "aphids"],
      commonDiseases: ["soft rot", "clubroot"]
    },
    {
      name: "Daikon Radish",
      scientificName: "Raphanus sativus var. longipinnatus",
      category: "VEGETABLES",
      description: "Large white Asian radish",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 7,
      daysToMaturity: 60,
      matureHeight: 2,
      companionPlants: ["lettuce", "peas"],
      commonPests: ["flea beetles"],
      commonDiseases: ["clubroot"]
    },
    {
      name: "Leeks",
      scientificName: "Allium ampeloprasum var. porrum",
      category: "VEGETABLES",
      description: "Mild onion family vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "BIENNIAL",
      plantingDepth: 0.5,
      plantSpacing: 6,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 120,
      matureHeight: 2,
      coldTolerant: true,
      companionPlants: ["carrot", "celery"],
      commonPests: ["onion fly", "thrips"],
      commonDiseases: ["rust", "white tip"]
    },
    {
      name: "Rhubarb",
      scientificName: "Rheum rhabarbarum",
      category: "VEGETABLES",
      description: "Tart stem vegetable for pies",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 36,
      rowSpacing: 48,
      daysToMaturity: 365,
      matureHeight: 3,
      matureSpread: 4,
      coldTolerant: true,
      companionPlants: ["beans", "kale"],
      commonPests: ["rhubarb weevil"],
      commonDiseases: ["crown rot", "leaf spot"]
    },
    {
      name: "Horseradish",
      scientificName: "Armoracia rusticana",
      category: "VEGETABLES",
      description: "Pungent root for condiments",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 12,
      plantSpacing: 18,
      rowSpacing: 30,
      daysToMaturity: 150,
      matureHeight: 3,
      coldTolerant: true,
      companionPlants: ["potatoes"],
      commonPests: ["flea beetles"],
      commonDiseases: ["white rust"]
    },
    {
      name: "Jerusalem Artichoke",
      scientificName: "Helianthus tuberosus",
      category: "VEGETABLES",
      description: "Crunchy tuber vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 4,
      plantSpacing: 24,
      rowSpacing: 36,
      daysToMaturity: 120,
      matureHeight: 10,
      droughtTolerant: true,
      companionPlants: ["beans"],
      commonPests: ["aphids"],
      commonDiseases: ["sclerotinia"]
    },
    {
      name: "Jicama",
      scientificName: "Pachyrhizus erosus",
      category: "VEGETABLES",
      description: "Crunchy tropical root vegetable",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 12,
      rowSpacing: 36,
      germinationDays: 14,
      daysToMaturity: 150,
      matureHeight: 2,
      heatTolerant: true,
      companionPlants: ["beans", "squash"],
      commonPests: ["aphids"],
      commonDiseases: ["root rot"]
    },
    {
      name: "Yam",
      scientificName: "Dioscorea alata",
      category: "VEGETABLES",
      description: "Starchy tropical tuber",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 4,
      plantSpacing: 36,
      rowSpacing: 48,
      daysToMaturity: 270,
      matureHeight: 8,
      heatTolerant: true,
      companionPlants: ["beans", "corn"],
      commonPests: ["yam beetle"],
      commonDiseases: ["anthracnose", "virus diseases"]
    },
    {
      name: "Cassava",
      scientificName: "Manihot esculenta",
      category: "VEGETABLES",
      description: "Starchy tropical root staple",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 36,
      rowSpacing: 48,
      daysToMaturity: 300,
      matureHeight: 8,
      droughtTolerant: true,
      heatTolerant: true,
      companionPlants: ["beans", "yam"],
      commonPests: ["mealybugs", "mites"],
      commonDiseases: ["mosaic virus", "bacterial blight"]
    },
    {
      name: "Taro",
      scientificName: "Colocasia esculenta",
      category: "VEGETABLES",
      description: "Tropical root vegetable",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 8,
      hardinessZoneMax: 11,
      soilTypes: ["CLAY", "LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "VERY_HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 3,
      plantSpacing: 24,
      rowSpacing: 36,
      daysToMaturity: 200,
      matureHeight: 4,
      companionPlants: ["sweet potato"],
      commonPests: ["aphids", "thrips"],
      commonDiseases: ["leaf blight", "root rot"]
    },
    {
      name: "Plantain",
      scientificName: "Musa paradisiaca",
      category: "VEGETABLES",
      description: "Starchy cooking banana",
      climateZones: ["TROPICAL", "SUBTROPICAL"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantSpacing: 120,
      daysToMaturity: 365,
      matureHeight: 15,
      matureSpread: 10,
      heatTolerant: true,
      companionPlants: ["ginger", "turmeric"],
      commonPests: ["nematodes", "weevil"],
      commonDiseases: ["panama disease", "sigatoka"]
    }
  ],

  // ==================== TREE NUTS ====================
  treeNuts: [
    {
      name: "Hazelnut",
      scientificName: "Corylus avellana",
      category: "NUTS",
      description: "Small sweet tree nut",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 180,
      daysToMaturity: 1095,
      matureHeight: 15,
      matureSpread: 15,
      companionPlants: ["comfrey", "chives"],
      commonPests: ["filbert worm"],
      commonDiseases: ["eastern filbert blight"]
    },
    {
      name: "Chestnut",
      scientificName: "Castanea mollissima",
      category: "NUTS",
      description: "Sweet edible tree nut",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 8,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 360,
      daysToMaturity: 2190,
      matureHeight: 40,
      matureSpread: 40,
      companionPlants: ["oak", "hickory"],
      commonPests: ["chestnut weevil"],
      commonDiseases: ["chestnut blight"]
    }
  ]
};