import { extendedProduceSeedData } from './produce-seed-data-extended'

export const produceSeedData = {
  // ==================== CROPS (GRAINS & CEREALS) ====================
  crops: [
    {
      name: "Corn",
      scientificName: "Zea mays",
      category: "CROPS",
      description: "Versatile cereal grain used for food, feed, and biofuel production",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1.5,
      plantSpacing: 8,
      rowSpacing: 30,
      germinationDays: 7,
      daysToMaturity: 90,
      matureHeight: 8,
      matureSpread: 2,
      companionPlants: ["beans", "squash", "pumpkin"],
      incompatibleWith: ["tomato"],
      commonPests: ["corn borer", "rootworm", "armyworm"],
      commonDiseases: ["gray leaf spot", "northern corn leaf blight"],
      varieties: [
        {
          name: "Field Corn",
          description: "Standard dent corn for livestock feed and processing",
          daysToMaturity: 120,
          yieldPerPlant: 0.5,
          yieldUnit: "lbs",
          marketDemand: "High",
          diseaseResistance: ["gray leaf spot"],
          droughtTolerant: true
        },
        {
          name: "Sweet Corn",
          description: "Fresh eating corn with high sugar content",
          daysToMaturity: 75,
          yieldPerPlant: 2,
          yieldUnit: "ears",
          marketDemand: "Medium",
          premiumVariety: true,
          color: "yellow"
        }
      ]
    },
    {
      name: "Wheat",
      scientificName: "Triticum aestivum",
      category: "CROPS",
      description: "Primary cereal grain for bread and flour production",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "CLAY_LOAM", "SILT_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 1,
      rowSpacing: 7,
      germinationDays: 7,
      daysToMaturity: 120,
      matureHeight: 4,
      companionPlants: ["legumes"],
      commonPests: ["aphids", "hessian fly"],
      commonDiseases: ["stripe rust", "fusarium blight"]
    },
    {
      name: "Soybeans",
      scientificName: "Glycine max",
      category: "CROPS",
      description: "Legume crop rich in protein and oil",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1.5,
      plantSpacing: 3,
      rowSpacing: 30,
      germinationDays: 7,
      daysToMaturity: 100,
      matureHeight: 3,
      companionPlants: ["corn"],
      commonPests: ["soybean aphid", "bean leaf beetle"],
      commonDiseases: ["white mold", "soybean rust"]
    },
    {
      name: "Rice",
      scientificName: "Oryza sativa",
      category: "CROPS",
      description: "Staple cereal grain for global food security",
      climateZones: ["TROPICAL", "SUBTROPICAL", "TEMPERATE"],
      hardinessZoneMin: 8,
      hardinessZoneMax: 11,
      soilTypes: ["CLAY", "CLAY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      waterRequirement: "VERY_HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 1,
      plantSpacing: 6,
      rowSpacing: 8,
      germinationDays: 10,
      daysToMaturity: 120,
      matureHeight: 4,
      commonPests: ["rice water weevil", "stem borer"],
      commonDiseases: ["blast", "sheath blight"]
    }
  ],

  // ==================== VEGETABLES ====================
  vegetables: [
    {
      name: "Tomato",
      scientificName: "Solanum lycopersicum",
      category: "VEGETABLES",
      description: "Popular fruit vegetable rich in lycopene and vitamins",
      climateZones: ["TEMPERATE", "SUBTROPICAL", "MEDITERRANEAN"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 6.8,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 24,
      rowSpacing: 36,
      germinationDays: 7,
      daysToMaturity: 75,
      matureHeight: 6,
      matureSpread: 3,
      companionPlants: ["basil", "marigold", "pepper"],
      incompatibleWith: ["corn", "broccoli"],
      commonPests: ["hornworm", "aphids", "whitefly"],
      commonDiseases: ["blight", "wilt", "mosaic virus"],
      varieties: [
        {
          name: "Cherokee Purple",
          description: "Large heirloom variety with exceptional flavor",
          daysToMaturity: 80,
          yieldPerPlant: 3,
          yieldUnit: "lbs",
          premiumVariety: true,
          color: "purple",
          size: "Large"
        },
        {
          name: "Roma",
          description: "Paste tomato ideal for canning and sauces",
          daysToMaturity: 75,
          yieldPerPlant: 2,
          yieldUnit: "lbs",
          marketDemand: "High",
          color: "red",
          shape: "plum"
        }
      ]
    },
    {
      name: "Carrot",
      scientificName: "Daucus carota",
      category: "VEGETABLES",
      description: "Root vegetable high in beta-carotene and fiber",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 6.8,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 2,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 70,
      matureHeight: 1,
      companionPlants: ["onion", "chives", "rosemary"],
      incompatibleWith: ["dill"],
      commonPests: ["carrot fly", "wireworm"],
      commonDiseases: ["leaf blight", "root rot"]
    },
    {
      name: "Lettuce",
      scientificName: "Lactuca sativa",
      category: "VEGETABLES",
      description: "Leafy green vegetable for fresh consumption",
      climateZones: ["TEMPERATE", "MEDITERRANEAN"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 8,
      rowSpacing: 12,
      germinationDays: 7,
      daysToMaturity: 45,
      matureHeight: 0.5,
      companionPlants: ["carrots", "radish", "onion"],
      commonPests: ["aphids", "slugs"],
      commonDiseases: ["downy mildew", "tip burn"]
    },
    {
      name: "Broccoli",
      scientificName: "Brassica oleracea",
      category: "VEGETABLES",
      description: "Nutritious cruciferous vegetable high in vitamins",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 18,
      rowSpacing: 24,
      germinationDays: 7,
      daysToMaturity: 70,
      matureHeight: 2,
      companionPlants: ["cabbage", "cauliflower"],
      incompatibleWith: ["tomato"],
      commonPests: ["cabbage worm", "aphids"],
      commonDiseases: ["clubroot", "black rot"]
    },
    {
      name: "Spinach",
      scientificName: "Spinacia oleracea",
      category: "VEGETABLES", 
      description: "Iron-rich leafy green vegetable",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.5,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 4,
      rowSpacing: 12,
      germinationDays: 7,
      daysToMaturity: 45,
      matureHeight: 0.5,
      companionPlants: ["lettuce", "radish"],
      commonPests: ["leaf miners", "aphids"],
      commonDiseases: ["downy mildew", "white rust"]
    },
    {
      name: "Onion",
      scientificName: "Allium cepa",
      category: "VEGETABLES",
      description: "Versatile bulb vegetable used worldwide",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.5,
      plantSpacing: 4,
      rowSpacing: 12,
      germinationDays: 10,
      daysToMaturity: 110,
      matureHeight: 1,
      companionPlants: ["carrot", "tomato", "cabbage"],
      commonPests: ["onion maggot", "thrips"],
      commonDiseases: ["downy mildew", "purple blotch"]
    },
    {
      name: "Potato",
      scientificName: "Solanum tuberosum",
      category: "VEGETABLES",
      description: "Starchy tuber vegetable staple food",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 5.0,
      soilPhMax: 6.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 4,
      plantSpacing: 12,
      rowSpacing: 36,
      germinationDays: 14,
      daysToMaturity: 90,
      matureHeight: 2,
      companionPlants: ["beans", "corn"],
      incompatibleWith: ["tomato", "sunflower"],
      commonPests: ["colorado potato beetle", "wireworm"],
      commonDiseases: ["late blight", "scab"]
    },
    {
      name: "Bell Pepper",
      scientificName: "Capsicum annuum",
      category: "VEGETABLES",
      description: "Sweet pepper variety rich in vitamin C",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 18,
      rowSpacing: 24,
      germinationDays: 10,
      daysToMaturity: 75,
      matureHeight: 3,
      companionPlants: ["tomato", "basil"],
      commonPests: ["aphids", "pepper weevil"],
      commonDiseases: ["bacterial spot", "mosaic virus"]
    }
  ],

  // ==================== FRUITS ====================
  fruits: [
    {
      name: "Apple",
      scientificName: "Malus domestica",
      category: "FRUITS",
      description: "Popular tree fruit with numerous culinary uses",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 180,
      rowSpacing: 240,
      daysToMaturity: 1095, // ~3 years to first fruit
      matureHeight: 20,
      matureSpread: 20,
      companionPlants: ["clover", "comfrey"],
      commonPests: ["codling moth", "apple maggot"],
      commonDiseases: ["fire blight", "apple scab"],
      varieties: [
        {
          name: "Honeycrisp",
          description: "Crisp texture with balanced sweet-tart flavor",
          yieldPerPlant: 150,
          yieldUnit: "lbs",
          premiumVariety: true,
          marketDemand: "High",
          coldTolerant: true,
          color: "red/yellow",
          size: "Large"
        },
        {
          name: "Granny Smith",
          description: "Tart green apple excellent for baking",
          yieldPerPlant: 120,
          yieldUnit: "lbs",
          marketDemand: "Medium",
          color: "green",
          size: "Medium"
        }
      ]
    },
    {
      name: "Strawberry",
      scientificName: "Fragaria × ananassa",
      category: "FRUITS",
      description: "Sweet berry fruit popular for fresh eating and processing",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0,
      plantSpacing: 12,
      rowSpacing: 36,
      germinationDays: 14,
      daysToMaturity: 60,
      matureHeight: 0.5,
      matureSpread: 1,
      companionPlants: ["thyme", "borage"],
      commonPests: ["spider mites", "slugs"],
      commonDiseases: ["gray mold", "leaf spot"]
    },
    {
      name: "Orange",
      scientificName: "Citrus sinensis",
      category: "FRUITS",
      description: "Citrus fruit high in vitamin C and fiber",
      climateZones: ["SUBTROPICAL", "MEDITERRANEAN"],
      hardinessZoneMin: 9,
      hardinessZoneMax: 11,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 240,
      daysToMaturity: 1095,
      matureHeight: 25,
      matureSpread: 20,
      commonPests: ["citrus psyllid", "scale insects"],
      commonDiseases: ["citrus canker", "greening disease"]
    },
    {
      name: "Grape",
      scientificName: "Vitis vinifera",
      category: "FRUITS",
      description: "Versatile fruit for fresh eating, wine, and juice",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 10,
      soilTypes: ["LOAM", "SANDY_LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 96,
      rowSpacing: 120,
      daysToMaturity: 730,
      matureHeight: 8,
      matureSpread: 6,
      droughtTolerant: true,
      companionPlants: ["roses", "lavender"],
      commonPests: ["grape phylloxera", "birds"],
      commonDiseases: ["powdery mildew", "downy mildew"]
    },
    {
      name: "Blueberry",
      scientificName: "Vaccinium corymbosum",
      category: "FRUITS",
      description: "Antioxidant-rich berry fruit with health benefits",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["SANDY", "PEAT"],
      soilPhMin: 4.5,
      soilPhMax: 5.5,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 72,
      rowSpacing: 120,
      daysToMaturity: 1095,
      matureHeight: 6,
      matureSpread: 6,
      companionPlants: ["azalea", "rhododendron"],
      commonPests: ["blueberry maggot", "aphids"],
      commonDiseases: ["mummy berry", "anthracnose"]
    }
  ],

  // ==================== TREES ====================
  trees: [
    {
      name: "Oak",
      scientificName: "Quercus",
      category: "TREES",
      description: "Hardwood tree valued for timber and wildlife habitat",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM", "SANDY_LOAM"],
      soilPhMin: 5.5,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 480,
      daysToMaturity: 7300, // ~20 years to maturity
      matureHeight: 80,
      matureSpread: 60,
      companionPlants: ["understory shrubs"],
      commonPests: ["oak borer", "gypsy moth"],
      commonDiseases: ["oak wilt", "powdery mildew"]
    },
    {
      name: "Pine",
      scientificName: "Pinus",
      category: "TREES",
      description: "Evergreen conifer valued for timber and landscaping",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 9,
      soilTypes: ["SANDY", "SANDY_LOAM", "LOAM"],
      soilPhMin: 4.5,
      soilPhMax: 7.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "EVERGREEN",
      plantSpacing: 240,
      daysToMaturity: 5475, // ~15 years
      matureHeight: 60,
      matureSpread: 30,
      droughtTolerant: true,
      commonPests: ["pine beetle", "sawfly"],
      commonDiseases: ["needle blight", "rust"]
    },
    {
      name: "Maple",
      scientificName: "Acer",
      category: "TREES",
      description: "Deciduous tree valued for timber and maple syrup",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 3,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "PARTIAL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 360,
      daysToMaturity: 7300,
      matureHeight: 75,
      matureSpread: 50,
      companionPlants: ["understory ferns"],
      commonPests: ["aphids", "scale insects"],
      commonDiseases: ["tar spot", "anthracnose"]
    },
    {
      name: "Cherry",
      scientificName: "Prunus avium",
      category: "TREES",
      description: "Fruit tree producing sweet or sour cherries",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 8,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 240,
      daysToMaturity: 1095,
      matureHeight: 30,
      matureSpread: 25,
      companionPlants: ["chives", "garlic"],
      commonPests: ["cherry fruit fly", "aphids"],
      commonDiseases: ["brown rot", "leaf spot"]
    }
  ],

  // ==================== HERBS ====================
  herbs: [
    {
      name: "Basil",
      scientificName: "Ocimum basilicum",
      category: "HERBS",
      description: "Aromatic herb popular in Mediterranean cuisine",
      climateZones: ["TEMPERATE", "SUBTROPICAL", "MEDITERRANEAN"],
      hardinessZoneMin: 2,
      hardinessZoneMax: 11,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "ANNUAL",
      plantingDepth: 0.25,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 7,
      daysToMaturity: 60,
      matureHeight: 2,
      companionPlants: ["tomato", "pepper"],
      commonPests: ["aphids", "spider mites"],
      commonDiseases: ["fusarium wilt", "bacterial leaf spot"]
    },
    {
      name: "Oregano",
      scientificName: "Origanum vulgare",
      category: "HERBS",
      description: "Mediterranean herb with strong aromatic flavor",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 10,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 12,
      rowSpacing: 18,
      germinationDays: 10,
      daysToMaturity: 90,
      matureHeight: 1,
      droughtTolerant: true,
      companionPlants: ["tomato", "pepper"],
      commonPests: ["spider mites", "aphids"],
      commonDiseases: ["root rot", "powdery mildew"]
    },
    {
      name: "Thyme",
      scientificName: "Thymus vulgaris",
      category: "HERBS",
      description: "Hardy perennial herb with culinary and medicinal uses",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 9,
      soilTypes: ["SANDY", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      waterRequirement: "VERY_LOW",
      sunRequirement: "FULL_SUN",
      growthHabit: "PERENNIAL",
      plantingDepth: 0.25,
      plantSpacing: 8,
      rowSpacing: 12,
      germinationDays: 14,
      daysToMaturity: 75,
      matureHeight: 0.5,
      matureSpread: 1,
      droughtTolerant: true,
      companionPlants: ["cabbage", "strawberry"],
      commonPests: ["spider mites"],
      commonDiseases: ["root rot"]
    }
  ],

  // ==================== NUTS ====================
  nuts: [
    {
      name: "Almond",
      scientificName: "Prunus dulcis",
      category: "NUTS",
      description: "Tree nut with high protein and healthy fats",
      climateZones: ["MEDITERRANEAN", "TEMPERATE"],
      hardinessZoneMin: 7,
      hardinessZoneMax: 9,
      soilTypes: ["SANDY_LOAM", "LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 240,
      daysToMaturity: 1095, // ~3 years to first nuts
      matureHeight: 25,
      matureSpread: 25,
      droughtTolerant: true,
      commonPests: ["navel orangeworm", "peach twig borer"],
      commonDiseases: ["brown rot", "hull rot"]
    },
    {
      name: "Walnut",
      scientificName: "Juglans regia",
      category: "NUTS",
      description: "Tree nut high in omega-3 fatty acids",
      climateZones: ["TEMPERATE", "CONTINENTAL"],
      hardinessZoneMin: 4,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "CLAY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      waterRequirement: "MODERATE",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 480,
      daysToMaturity: 1825, // ~5 years to first nuts
      matureHeight: 60,
      matureSpread: 60,
      companionPlants: ["grasses"],
      incompatibleWith: ["apple", "pine"], // allelopathic
      commonPests: ["walnut husk fly", "codling moth"],
      commonDiseases: ["walnut blight", "thousand cankers"]
    },
    {
      name: "Pecan",
      scientificName: "Carya illinoinensis",
      category: "NUTS",
      description: "Native American tree nut with rich flavor",
      climateZones: ["TEMPERATE", "SUBTROPICAL"],
      hardinessZoneMin: 6,
      hardinessZoneMax: 9,
      soilTypes: ["LOAM", "SANDY_LOAM"],
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      waterRequirement: "HIGH",
      sunRequirement: "FULL_SUN",
      growthHabit: "DECIDUOUS",
      plantSpacing: 480,
      daysToMaturity: 2555, // ~7 years to first nuts
      matureHeight: 75,
      matureSpread: 75,
      commonPests: ["pecan weevil", "aphids"],
      commonDiseases: ["scab", "anthracnose"]
    }
  ],

  // Add all extended categories
  ...extendedProduceSeedData
};

export const nutritionalSeedData = [
  {
    produceTypeName: "Tomato",
    calories: 18,
    protein: 0.9,
    carbohydrates: 3.9,
    fiber: 1.2,
    sugar: 2.6,
    fat: 0.2,
    vitaminA: 42,
    vitaminC: 14,
    vitaminK: 8,
    potassium: 237,
    calcium: 10,
    iron: 0.3
  },
  {
    produceTypeName: "Carrot",
    calories: 41,
    protein: 0.9,
    carbohydrates: 9.6,
    fiber: 2.8,
    sugar: 4.7,
    fat: 0.2,
    vitaminA: 184,
    vitaminC: 6,
    vitaminK: 13,
    potassium: 320,
    calcium: 33,
    iron: 0.3
  },
  {
    produceTypeName: "Apple",
    calories: 52,
    protein: 0.3,
    carbohydrates: 14,
    fiber: 2.4,
    sugar: 10,
    fat: 0.2,
    vitaminC: 5,
    potassium: 107,
    calcium: 6,
    iron: 0.1
  },
  {
    produceTypeName: "Broccoli",
    calories: 34,
    protein: 2.8,
    carbohydrates: 7,
    fiber: 2.6,
    sugar: 1.5,
    fat: 0.4,
    vitaminA: 12,
    vitaminC: 89,
    vitaminK: 102,
    calcium: 47,
    iron: 0.7,
    potassium: 316
  },
  {
    produceTypeName: "Spinach",
    calories: 23,
    protein: 2.9,
    carbohydrates: 3.6,
    fiber: 2.2,
    sugar: 0.4,
    fat: 0.4,
    vitaminA: 188,
    vitaminC: 28,
    vitaminK: 483,
    calcium: 99,
    iron: 2.7,
    potassium: 558
  },
  {
    produceTypeName: "Kale",
    calories: 49,
    protein: 4.3,
    carbohydrates: 9,
    fiber: 3.6,
    sugar: 2.3,
    fat: 0.9,
    vitaminA: 206,
    vitaminC: 120,
    vitaminK: 704,
    calcium: 150,
    iron: 1.5,
    potassium: 491
  },
  {
    produceTypeName: "Sweet Potato",
    calories: 86,
    protein: 1.6,
    carbohydrates: 20,
    fiber: 3,
    sugar: 4.2,
    fat: 0.1,
    vitaminA: 284,
    vitaminC: 2.4,
    potassium: 337,
    calcium: 30,
    iron: 0.6
  },
  {
    produceTypeName: "Garlic",
    calories: 149,
    protein: 6.4,
    carbohydrates: 33,
    fiber: 2.1,
    sugar: 1,
    fat: 0.5,
    vitaminC: 31,
    calcium: 181,
    iron: 1.7,
    potassium: 401
  },
  {
    produceTypeName: "Avocado",
    calories: 160,
    protein: 2,
    carbohydrates: 9,
    fiber: 7,
    sugar: 0.7,
    fat: 15,
    vitaminC: 10,
    vitaminE: 10,
    vitaminK: 21,
    potassium: 485,
    calcium: 12
  }
];

export const plantingCalendarSeedData = [
  // Corn planting schedules by region
  {
    produceTypeName: "Corn",
    region: "Midwest US",
    springPlantStart: 4, // April
    springPlantEnd: 6,   // June
    harvestStart: 9,     // September
    harvestEnd: 11,      // November
    indoorStartWeeks: 2
  },
  {
    produceTypeName: "Corn",
    region: "Southeast US",
    springPlantStart: 3, // March
    springPlantEnd: 5,   // May
    fallPlantStart: 8,   // August
    fallPlantEnd: 9,     // September
    harvestStart: 6,     // June
    harvestEnd: 10       // October
  },
  
  // Tomato planting schedules
  {
    produceTypeName: "Tomato",
    region: "Temperate North",
    springPlantStart: 5, // May (after last frost)
    springPlantEnd: 6,   // June
    harvestStart: 7,     // July
    harvestEnd: 10,      // October
    indoorStartWeeks: 6
  },
  {
    produceTypeName: "Tomato",
    region: "Southern US",
    springPlantStart: 3, // March
    springPlantEnd: 4,   // April
    fallPlantStart: 8,   // August
    fallPlantEnd: 9,     // September
    harvestStart: 5,     // May
    harvestEnd: 11,      // November
    indoorStartWeeks: 4
  },
  
  // Lettuce planting (succession planting)
  {
    produceTypeName: "Lettuce",
    region: "Cool Climate",
    springPlantStart: 3, // March
    springPlantEnd: 5,   // May
    fallPlantStart: 8,   // August
    fallPlantEnd: 10,    // October
    harvestStart: 5,     // May
    harvestEnd: 11,      // November
    notes: "Plant every 2 weeks for continuous harvest"
  }
];